<a href="https://colab.research.google.com/github/ajaykm000563/Wine-Quality-Prediction-Model/blob/main/Wine_Quality_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Wine Quality

Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).

Dataset Characteristics
Multivariate

Subject Area
Business

Associated Tasks
Classification, Regression

Feature Type
Real

# Instances
4898

# Features
11

# Additional Information

The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine. For more details, consult: http://www.vinhoverde.pt/en/ or the reference [Cortez et al., 2009].  Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).

These datasets can be viewed as classification or regression tasks.  The classes are ordered and not balanced (e.g. there are many more normal wines than excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent or poor wines. Also, we are not sure if all input variables are relevant. So it could be interesting to test feature selection methods.           

For more information, read [Cortez et al., 2009].

Input variables (based on physicochemical tests):

   1 - fixed acidity

   2 - volatile acidity

   3 - citric acid

   4 - residual sugar

   5 - chlorides

   6 - free sulfur dioxide

   7 - total sulfur dioxide

   8 - density

   9 - pH

   10 - sulphates

   11 - alcohol

Output variable (based on sensory data):

   12 - quality (score between 0 and 10)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Loading the dataset
import pandas as pd

df_red = pd.read_csv('winequality-red.csv',sep=';')
df_white = pd.read_csv('winequality-white.csv',sep=';')

In [ ]:
df_red['color'] = 0
df_white['color'] = 1

In [ ]:
df = pd.concat([df_red,df_white])

In [ ]:
df.shape

(6497, 13)

In [ ]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0

In [ ]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  color                 6497 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 710.6 KB

In [ ]:
# Searching any null values
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
color                   0
dtype: int64

In [ ]:
# Trying to find the relation between features
df.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,color
fixed acidity,1.000000,0.219008,0.324436,-0.111981,0.298195,-0.282735,-0.329054,0.458910,-0.252700,0.299568,-0.095452,-0.076743,-0.486740
volatile acidity,0.219008,1.000000,-0.377981,-0.196011,0.377124,-0.352557,-0.414476,0.271296,0.261454,0.225984,-0.037640,-0.265699,-0.653036
citric acid,0.324436,-0.377981,1.000000,0.142451,0.038998,0.133126,0.195242,0.096154,-0.329808,0.056197,-0.010493,0.085532,0.187397
residual sugar,-0.111981,-0.196011,0.142451,1.000000,-0.128940,0.402871,0.495482,0.552517,-0.267320,-0.185927,-0.359415,-0.036980,0.348821
chlorides,0.298195,0.377124,0.038998,-0.128940,1.000000,-0.195045,-0.279630,0.362615,0.044708,0.395593,-0.256916,-0.200666,-0.512678
free sulfur dioxide,-0.282735,-0.352557,0.133126,0.402871,-0.195045,1.000000,0.720934,0.025717,-0.145854,-0.188457,-0.179838,0.055463,0.471644
total sulfur dioxide,-0.329054,-0.414476,0.195242,0.495482,-0.279630,0.720934,1.000000,0.032395,-0.238413,-0.275727,-0.265740,-0.041385,0.700357
density,0.458910,0.271296,0.096154,0.552517,0.362615,0.025717,0.032395,1.000000,0.011686,0.259478,-0.686745,-0.305858,-0.390645
pH,-0.252700,0.261454,-0.329808,-0.267320,0.044708,-0.145854,-0.238413,0.011686,1.000000,0.192123,0.121248,0.019506,-0.329129
sulphates,0.299568,0.225984,0.056197,-0.185927,0.395593,-0.188457,-0.275727,0.259478,0.192123,1.000000,-0.003029,0.038485,-0.487218
alcohol,-0.095452,-0.037640,-0.010493,-0.359415,-0.256916,-0.179838,-0.265740,-0.686745,0.121248,-0.003029,1.000000,0.444319,0.032970
quality,-0.076743,-0.265699,0.085532,-0.036980,-0.200666,0.055463,-0.041385,-0.305858,0.019506,0.038485,0.444319,1.000000,0.119323
color,-0.486740,-0.653036,0.187397,0.348821,-0.512678,0.471644,0.700357,-0.390645,-0.329129,-0.487218,0.032970,0.119323,1.000000

In [ ]:
# Dviding the dataset into dependent and independent
X = df.drop('quality',axis=1)
y = df['quality']

In [ ]:
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,color
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,1
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,1
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,1
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,1
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,1

In [ ]:
y

0       5
1       5
2       5
3       6
4       5
       ..
4893    6
4894    5
4895    6
4896    7
4897    6
Name: quality, Length: 6497, dtype: int64

In [ ]:
y.value_counts()

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

In [ ]:
# Dividing the dataset into training and testing and shfling and balancing the multiclass
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,color
3161,6.1,0.17,0.42,15.1,0.033,28.0,124.0,0.99684,2.87,0.47,9.5,1
2566,6.9,0.21,0.24,1.8,0.021,17.0,80.0,0.98992,3.15,0.46,12.3,1
931,6.4,0.26,0.43,12.6,0.033,64.0,230.0,0.99740,3.08,0.38,8.9,1
1479,7.7,0.16,0.49,2.0,0.056,20.0,124.0,0.99480,3.32,0.49,10.7,1
4137,7.4,0.31,0.26,8.6,0.048,47.0,206.0,0.99640,3.26,0.36,9.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3018,6.8,0.22,0.31,6.9,0.037,33.0,121.0,0.99176,3.02,0.39,11.9,1
4044,7.4,0.16,0.27,15.5,0.050,25.0,135.0,0.99840,2.90,0.43,8.7,1
3992,6.7,0.19,0.32,3.7,0.041,26.0,76.0,0.99173,2.90,0.57,10.5,1
1584,6.4,0.25,0.74,7.8,0.045,52.0,209.0,0.99560,3.21,0.42,9.2,1
4821,7.0,0.24,0.47,1.3,0.043,18.0,131.0,0.99176,3.19,0.45,11.0,1

In [ ]:
y_train

3161    5
2566    7
931     5
1479    6
4137    5
       ..
3018    8
4044    7
3992    7
1584    6
4821    6
Name: quality, Length: 5197, dtype: int64

In [ ]:
# Standardizing the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [ ]:
# List of Regression Algorithms
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor

# Dictionary of models
models = {
   'Linear Regression': LinearRegression(),
   'KNN': KNeighborsRegressor(),
   'Ridge': Ridge(),
   'Lasso': Lasso(),
   'SVR': SVR(),
   'Decision Tree': DecisionTreeRegressor(),
   'Random Forest': RandomForestRegressor(),
   'Gradient Boosting': GradientBoostingRegressor(),
   'AdaBoost': AdaBoostRegressor(),
   'XGBoost': XGBRegressor()
}

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    n = len(y_test)
    p = X_test.shape[1]
    adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

    print(f"{model_name}:")
    print(f"  MAE: {mae:.2f}")
    print(f"  MSE: {mse:.2f}")
    print(f"  R2 Score: {r2:.2f}")
    print(f"  Adjusted R2 Score: {adjusted_r2:.2f}")
    print("--------------*------------------")

Linear Regression:
  MAE: 0.57
  MSE: 0.53
  R2 Score: 0.31
  Adjusted R2 Score: 0.30
--------------*------------------
KNN:
  MAE: 0.53
  MSE: 0.49
  R2 Score: 0.35
  Adjusted R2 Score: 0.35
--------------*------------------
Ridge:
  MAE: 0.57
  MSE: 0.53
  R2 Score: 0.31
  Adjusted R2 Score: 0.30
--------------*------------------
Lasso:
  MAE: 0.69
  MSE: 0.76
  R2 Score: -0.00
  Adjusted R2 Score: -0.01
--------------*------------------
SVR:
  MAE: 0.51
  MSE: 0.46
  R2 Score: 0.40
  Adjusted R2 Score: 0.40
--------------*------------------
Decision Tree:
  MAE: 0.49
  MSE: 0.71
  R2 Score: 0.07
  Adjusted R2 Score: 0.06
--------------*------------------
Random Forest:
  MAE: 0.43
  MSE: 0.37
  R2 Score: 0.51
  Adjusted R2 Score: 0.51
--------------*------------------
Gradient Boosting:
  MAE: 0.53
  MSE: 0.46
  R2 Score: 0.40
  Adjusted R2 Score: 0.40
--------------*------------------
AdaBoost:
  MAE: 0.60
  MSE: 0.54
  R2 Score: 0.29
  Adjusted R2 Score: 0.28
--------------*------------------
XGBoost:
  MAE: 0.46
  MSE: 0.40
  R2 Score: 0.48
  Adjusted R2 Score: 0.48
--------------*------------------

In [ ]:
# List of Classification Algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

# Dictionary of models
models = {
   'Logistic Regression': LogisticRegression(multi_class='ovr'),
   'KNN': KNeighborsClassifier(),
   'SVC': SVC(),
   'Decision Tree': DecisionTreeClassifier(),
   'Random Forest': RandomForestClassifier(),
   'Gradient Boosting': GradientBoostingClassifier(),
   'AdaBoost': AdaBoostClassifier(),
}

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
for model_name, model in models.items():
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    print(f"{model_name}:")
    print(f"  Accuracy: {accuracy:.2f}")
    print(f"  Precision: {precision:.2f}")
    print(f"  Recall: {recall:.2f}")
    print(f"  F1 Score: {f1:.2f}")
    print("--------------*------------------")

Logistic Regression:
  Accuracy: 0.53
  Precision: 0.54
  Recall: 0.53
  F1 Score: 0.49
--------------*------------------
KNN:
  Accuracy: 0.56
  Precision: 0.54
  Recall: 0.56
  F1 Score: 0.55
--------------*------------------
SVC:
  Accuracy: 0.57
  Precision: 0.57
  Recall: 0.57
  F1 Score: 0.54
--------------*------------------
Decision Tree:
  Accuracy: 0.60
  Precision: 0.60
  Recall: 0.60
  F1 Score: 0.60
--------------*------------------
Random Forest:
  Accuracy: 0.69
  Precision: 0.69
  Recall: 0.69
  F1 Score: 0.68
--------------*------------------
Gradient Boosting:
  Accuracy: 0.59
  Precision: 0.59
  Recall: 0.59
  F1 Score: 0.58
--------------*------------------
AdaBoost:
  Accuracy: 0.45
  Precision: 0.42
  Recall: 0.45
  F1 Score: 0.40
--------------*------------------

In [ ]:
# Hyper parameter tuning of random forest model using RandmizedSearch CV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
params = {
    'n_estimators': [100,50,150,70,25],
    'criterion': ['gini','entropy','log_loss'],
    'max_depth': [5,10,15,20,50,100],
    'min_samples_split': [2,5,10,15,25],
    'class_weight':['balanced','balanced_subsample'],
    'max_features':['auto','sqrt','log2']
}

In [ ]:
rcv = RandomizedSearchCV(model,params,cv=5,verbose=2,n_jobs=-1)
rcv.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'class_weight': ['balanced',
                                                         'balanced_subsample'],
                                        'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_depth': [5, 10, 15, 20, 50, 100],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_split': [2, 5, 10, 15, 25],
                                        'n_estimators': [100, 50, 150, 70, 25]},
                   verbose=2)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = rcv.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print(f"{model_name}:")
print(f"  Accuracy: {accuracy:.2f}")
print(f"  Precision: {precision:.2f}")
print(f"  Recall: {recall:.2f}")
print(f"  F1 Score: {f1:.2f}")

AdaBoost:
  Accuracy: 0.64
  Precision: 0.64
  Recall: 0.64
  F1 Score: 0.64

In [ ]:
# Hyper parameter tuning of random forest model using RandmizedSearch CV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
params = {
    'n_estimators': [100,50,150,70,25],
    'criterion': ['squared_error','absolute_error','friedman_mse','poisson'],
    'max_depth': [5,10,15,20,50,100],
    'min_samples_split': [2,5,10,15,25],
    'max_features':['auto','sqrt','log2']
}

In [ ]:
rcv = RandomizedSearchCV(model,params,cv=5,verbose=2,n_jobs=-1)
rcv.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'criterion': ['squared_error',
                                                      'absolute_error',
                                                      'friedman_mse',
                                                      'poisson'],
                                        'max_depth': [5, 10, 15, 20, 50, 100],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_split': [2, 5, 10, 15, 25],
                                        'n_estimators': [100, 50, 150, 70, 25]},
                   verbose=2)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = rcv.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("mae :" ,mae)
print("mse :" ,mse)
print("r2_score :" , r2)

mae : 0.4426670065162871
mse : 0.3667833931816154
r2_score : 0.5195877355781287